travis:
  secure:
    BINSTAR_TOKEN: Fbo3JuRT7hLZGvLfpbXcYPS0vKkgzVasNdQx9FaG6mIQwXA0CpvjCXicbSwmx9uL5nU7lj0TPV7Zx8JZC9gOuch/N02iAWkmBwb5HW8rmgNdEwJc3CnEUoXB3LtWSnLv+Sbimhev/qMejk5c2ITSaH0/kWS1xOYcZXSrl/Uffs7FV0EvhBjb0heNNE7Ww4iSaqWt8W4fynHRyh0SX8j3grr0hMeien7FQCnqEYxV15XvM6yq6DsmVidPXmY9lT7WnRn3NJ3KkVTC5bM6diJVcAN3CvUVnnPCB/6fCykDGAf+eS72v7Wwppd2rKuUv1Tk6AC28MW5/pay/Ha5rMBkPxciJodWCzChWtmsWZy6/I9ya6wah0M8q6zJkZNvDRcubFqmQYO2j5OoBvUGh4ztTI9lKBzZhBp1DVFSwcjUkZfbpwELFuoDzYh7M+siw2nc8WzXCog/wAydNRuMjXHes3RSAZW7kWv0o5rNssVR2oqwV7a5eupXiiBM7VQEiIIx4yWhT1X5znLHbFxPzq2yC0UWFPCNKfwi2K6n+hTZxSB3dp6rHIsMRCmkVj306rYWkRIWGSTAD2O+wZN1zPi8x5N59RTvTjG62RYF9eP9D0ekzwcHPorUVyIRmBUrgRZJ+fjgA87DDN8b7Jm2hY5yTKKBtVX/EMLU1q21ITSvQ6s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
